loot-chest-protection:
  protected-worlds:
    - Resource
    - Resource_nether
    - Resource_the_end

nicknames:
  max-length: 16
  min-length: 3
  blacklisted-names:
    - admin
    - administrator
    - server
    - staff
    - helper
    - owner
    - moderator
    - mod