# How often to save things to the database (in seconds)
# Setting this too high comes with a risk of data loss if the server crashes.
database-save-interval: 300

# DO NOT TOUCH THIS VALUE!!!
config-version: 1