name: Skylight
version: '${project.version}'
main: uk.firedev.skylight.Skylight
api-version: '1.20'
author: FireML
dependencies:
  server:
    Vault:
      required: true
      load: BEFORE
    DaisyLib:
      required: true
      load: BEFORE
    CMI:
      required: false
      load: BEFORE
    PlaceholderAPI:
      required: false
      load: BEFORE
    MiniPlaceholders:
      required: false
      load: BEFORE