name: Skylight
version: '${project.version}'
main: uk.firedev.skylight.Skylight
api-version: '1.20'
author: FireML
depend:
  - DaisyLib
  - Vault
softdepend:
  - PlaceholderAPI
  - CMI
commands:
  elevator:
    description: "Manage Elevators"
    permission: skylight.command.elevator
  title:
    description: "Manage Titles"
    permission: skylight.command.title