name: Skylight
version: '${project.version}'
main: uk.firedev.skylight.Skylight
api-version: '1.20'
author: FireML
depend:
  - DaisyLib
  - Vault
softdepend:
  - PlaceholderAPI
  - CMI
commands:
  skylight:
    description: "Manage the Plugin"
    permission: skylight.command.main
  elevator:
    description: "Manage Elevators"
    permission: skylight.command.elevator
  prefix:
    description: "Manage Prefix"
    permission: skylight.command.prefix
  suffix:
    description: "Manage Suffix"
    permission: skylight.command.suffix
  amethystprotect:
    description: "Protects Amethyst"
  awardkit:
    description: "Give kits to people"
    permission: skylight.command.awardkit